begin;
select no_plan();
insert into auth.users(id) values
 ('00000000-0000-0000-0000-000000003801'),('00000000-0000-0000-0000-000000003802'),
 ('00000000-0000-0000-0000-000000003803'),('00000000-0000-0000-0000-000000003804'),
 ('00000000-0000-0000-0000-000000003805'),('00000000-0000-0000-0000-000000003806');
update public.profiles set id='crowd-a',handle='crowd_a' where auth_user_id='00000000-0000-0000-0000-000000003801';
update public.profiles set id='crowd-b',handle='crowd_b' where auth_user_id='00000000-0000-0000-0000-000000003802';
update public.profiles set id='crowd-s',handle='crowd_s' where auth_user_id='00000000-0000-0000-0000-000000003803';
update public.profiles set id='crowd-v',handle='crowd_v' where auth_user_id='00000000-0000-0000-0000-000000003804';
update public.profiles set id='crowd-o',handle='crowd_o' where auth_user_id='00000000-0000-0000-0000-000000003805';
update public.profiles set id='crowd-mod',handle='crowd_mod',role='moderator',moderated_hoods=array['techtakes']::public.hood_id[] where auth_user_id='00000000-0000-0000-0000-000000003806';
insert into public.takes(id,author_id,hood,text) values('crowd-take','crowd-a','techtakes','Crowd test proposition');
create temporary table crowd_duel as select public.create_arena_duel('crowd-take','crowd-b','00000000-0000-0000-0000-000000003810') payload;
grant select on crowd_duel to authenticated;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from crowd_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from crowd_duel$$;
select ok((select relrowsecurity from pg_class where oid='public.arena_crowd_messages'::regclass),'Crowd has RLS');
select ok(not has_table_privilege('anon','public.arena_crowd_messages','select'),'anonymous has no table access');
select ok(not has_table_privilege('authenticated','public.arena_crowd_messages','insert'),'client inserts denied');
select ok(not has_table_privilege('authenticated','public.arena_crowd_messages','update'),'client updates denied');
select ok(not has_table_privilege('authenticated','public.arena_crowd_messages','delete'),'client deletion denied');
select ok(not has_column_privilege('authenticated','public.arena_crowd_messages','request_key','select'),'idempotency key private');
select ok(not has_function_privilege('authenticated','public.submit_report_before_crowd(public.report_target,text,public.report_reason,text)','execute'),'report bypass private');
select ok(not has_function_privilege('anon','public.post_arena_crowd_message(text,text,uuid)','execute'),'anonymous posting RPC denied');
select ok(exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename='arena_crowd_messages'),'Crowd is published for authorized Realtime');
select throws_ok($$select public.get_arena_crowd(pg_temp.r())$$,'42501',null,'guest context denied');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003803","role":"authenticated"}',true);
select throws_ok($$select public.get_arena_crowd(pg_temp.r())$$,'42501',null,'nonmember context denied');
select lives_ok($$select public.watch_arena_room(pg_temp.r())$$,'spectator joins');
select is(public.get_arena_crowd(pg_temp.r())->>'spectatorCount','1','real spectator membership count');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'  ',gen_random_uuid())$$,'22023',null,'whitespace rejected');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),chr(160)||chr(8203),gen_random_uuid())$$,'22023',null,'invisible whitespace rejected');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),repeat('x',501),gen_random_uuid())$$,'22023',null,'oversize rejected');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Hello',null)$$,'22023',null,'request key required');
create temporary table crowd_first as select public.post_arena_crowd_message(pg_temp.r(),'Hello from the audience','00000000-0000-0000-0000-000000003820') payload;
grant select on crowd_first to authenticated;
create function pg_temp.mid() returns uuid language sql as $$select (payload->>'id')::uuid from crowd_first$$;
select is(public.post_arena_crowd_message(pg_temp.r(),'Hello from the audience','00000000-0000-0000-0000-000000003820')->>'id',pg_temp.mid()::text,'retry deduplicates');
select is((select count(*)::integer from public.rate_limit_events where actor_id='crowd-s' and action='arena_crowd_burst'),1,'retry charges one rate event');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Changed','00000000-0000-0000-0000-000000003820')$$,'P0006',null,'changed retry rejected');
select is((select count(*)::integer from public.arena_room_messages where room_id=pg_temp.r()),0,'Crowd does not enter argument transcript');
select is((select count(*)::integer from public.arena_room_participants where room_id=pg_temp.r() and role='debater'),2,'exactly two fighters');
select throws_ok($$select public.post_arena_room_message(pg_temp.r(),'Official impersonation')$$,'42501',null,'audience still cannot publish arguments');
select throws_ok($$select public.list_arena_crowd_messages(pg_temp.r(),null,null,'older',101)$$,'22023',null,'bounded pagination');
select throws_ok($$select public.list_arena_crowd_messages(pg_temp.r(),now(),null)$$,'22023',null,'partial cursor rejected');
select throws_ok($$select public.get_arena_crowd_messages(pg_temp.r(),array_fill(gen_random_uuid(),array[101]))$$,'22023',null,'hydration bounded');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003804","role":"authenticated"}',true);
select lives_ok($$select public.watch_arena_room(pg_temp.r())$$,'second spectator joins');
select is(public.get_arena_crowd(pg_temp.r())->>'spectatorCount','2','count follows real membership');
set local role authenticated;
select is((select count(*)::integer from public.arena_crowd_messages),1,'direct RLS member read works');
select is(jsonb_array_length(public.list_arena_crowd_messages(pg_temp.r())),1,'second session retrieves message');
select lives_ok($$select public.submit_report('arena_crowd_message',pg_temp.mid()::text,'spam')$$,'visible message report');
select throws_ok($$select public.moderate_arena_crowd_message(pg_temp.mid(),true,'spam')$$,'42501',null,'nonmoderator cannot hide');
reset role;
insert into public.mutes(muter_id,muted_id) values('crowd-v','crowd-s');
set local role authenticated;
select is((select count(*)::integer from public.arena_crowd_messages),0,'mute enforced in direct RLS');
select is(jsonb_array_length(public.get_arena_crowd_messages(pg_temp.r(),array[pg_temp.mid()])),0,'mute evicts hydrated messages');
reset role;
delete from public.mutes where muter_id='crowd-v';
insert into public.blocks(blocker_id,blocked_id) values('crowd-s','crowd-v');
set local role authenticated;
select is(jsonb_array_length(public.list_arena_crowd_messages(pg_temp.r())),0,'reverse block hides chat');
reset role;
delete from public.blocks where blocker_id='crowd-s';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003805","role":"authenticated"}',true);
set local role authenticated;
select is((select count(*)::integer from public.arena_crowd_messages),0,'outsider direct RLS denied');
select throws_ok($$select public.list_arena_crowd_messages(pg_temp.r())$$,'42501',null,'outsider list denied');
select throws_ok($$select public.submit_report('arena_crowd_message',pg_temp.mid()::text,'spam')$$,'42501',null,'private target reporting oracle denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003806","role":"authenticated"}',true);
select lives_ok($$select public.moderate_arena_crowd_message(pg_temp.mid(),true,'spam')$$,'scoped moderation hides');
select is((select count(*)::integer from public.moderation_actions where target_id=pg_temp.mid()::text),1,'moderation audited');
update public.profiles set moderated_hoods='{}' where id='crowd-mod';
select throws_ok($$select public.moderate_arena_crowd_message(pg_temp.mid(),false,'wrong hood')$$,'42501',null,'unrelated Hood moderator denied');
update public.profiles set moderated_hoods=array['techtakes']::public.hood_id[] where id='crowd-mod';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003803","role":"authenticated"}',true);
select is(jsonb_array_length(public.list_arena_crowd_messages(pg_temp.r())),0,'hidden excluded even from author');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Hello from the audience','00000000-0000-0000-0000-000000003820')$$,'42501',null,'retry cannot resurrect hidden content');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003806","role":"authenticated"}',true);
select lives_ok($$select public.moderate_arena_crowd_message(pg_temp.mid(),false,'restored')$$,'restore audited');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000003803","role":"authenticated"}',true);
insert into public.mutes(muter_id,muted_id) values('crowd-a','crowd-s');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Muted by fighter',gen_random_uuid())$$,'P0003',null,'fighter mute prevents new sends');
delete from public.mutes where muter_id='crowd-a';
select lives_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Burst 2',gen_random_uuid())$$,'burst second send');
select lives_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Burst 3',gen_random_uuid())$$,'burst third send');
select lives_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Burst 4',gen_random_uuid())$$,'burst fourth send');
select lives_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Burst 5',gen_random_uuid())$$,'burst fifth send');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Burst 6',gen_random_uuid())$$,'P0001',null,'burst rate enforced');
select is(jsonb_array_length(public.list_arena_crowd_messages(pg_temp.r(),null,null,'older',2)),2,'page limit respected');
select is(jsonb_array_length(public.list_arena_crowd_messages(pg_temp.r(),(select (payload->>'createdAt')::timestamptz from crowd_first),pg_temp.mid(),'newer')),4,'forward gap pagination');
delete from public.rate_limit_events where actor_id='crowd-s' and action='arena_crowd_burst';
insert into public.rate_limit_events(actor_id,action) select 'crowd-s','arena_crowd_message' from generate_series(1,25);
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'Long window exceeded',gen_random_uuid())$$,'P0001',null,'sustained rate enforced independently of burst');
select is((select count(*)::integer from public.rate_limit_events where actor_id='crowd-s' and action='arena_crowd_burst'),0,'failed sustained send rolls back burst charge');
insert into public.arena_daily_topics(id,title,status,opens_at,final_arguments_at,judging_at,closes_at)
 values('crowd-group-topic','Legacy group','live',now()-interval '1 hour',now()+interval '20 minutes',now()+interval '25 minutes',now()+interval '30 minutes');
insert into public.arena_rooms(id,topic_id,capacity,opens_at,closes_at)
 values('crowd-group-room','crowd-group-topic',40,now()-interval '1 hour',now()+interval '30 minutes');
select lives_ok($$select public.watch_arena_room('crowd-group-room')$$,'legacy GROUP entry unchanged');
select throws_ok($$select public.get_arena_crowd('crowd-group-room')$$,'42501',null,'Crowd limited to canonical DUEL');
do $$ begin
 update public.clashes set opens_at=now()-interval '1 hour',closes_at=now()-interval '1 second' where id=pg_temp.c();
 update public.arena_rooms set opens_at=now()-interval '1 hour',closes_at=now()-interval '1 second' where id=pg_temp.r();
 update public.arena_daily_topics set opens_at=now()-interval '1 hour',final_arguments_at=now()-interval '30 minutes',judging_at=now()-interval '5 minutes',closes_at=now()-interval '1 second'
 where id=(select topic_id from public.arena_rooms where id=pg_temp.r());
end $$;
select is(public.get_arena_crowd(pg_temp.r())->>'canSend','false','server deadline overrides stale OPEN Room');
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'After server close',gen_random_uuid())$$,'P0003',null,'post-close publishing denied');
select is(public.post_arena_crowd_message(pg_temp.r(),'Hello from the audience','00000000-0000-0000-0000-000000003820')->>'id',pg_temp.mid()::text,'closed retry acknowledges existing row without new write');
do $$ begin
  update public.clashes set status='cancelled' where id=pg_temp.c();
  update public.arena_rooms set status='CANCELLED' where id=pg_temp.r();
end $$;
select throws_ok($$select public.post_arena_crowd_message(pg_temp.r(),'After cancellation',gen_random_uuid())$$,'42501',null,'cancelled chat denied');
set local role authenticated;
select is((select count(*)::integer from public.arena_crowd_messages),0,'cancelled direct read denied');
reset role;
select * from finish();
rollback;
