begin;
select no_plan();
insert into auth.users(id) values ('00000000-0000-0000-0000-000000005101');
insert into public.profiles(id,handle,name) values ('security-hidden-a','security_hidden_a','Hidden A'),('security-hidden-b','security_hidden_b','Hidden B');
insert into public.mutes(muter_id,muted_id) values('security-hidden-a','security-hidden-b');
select ok(not has_function_privilege('authenticated','public.arena_actor_hidden_internal(text,text)','execute'),'internal helper private');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname like '%crew%' and has_function_privilege('anon',p.oid,'execute')),'no anonymous Crew function grants');
select ok(not has_function_privilege('authenticated','public.arena_crew_payload(public.arena_crews)','execute'),'Crew payload helper private');
select ok(not has_function_privilege('authenticated','public.arena_assert_crew_join_allowed(text)','execute'),'arbitrary membership eligibility helper private');
set local role anon;
select throws_ok($$select public.arena_actor_hidden('security-hidden-a','security-hidden-b')$$,'42501',null,'anonymous relationship oracle denied');
select throws_ok($$select public.explore_actor_hidden('security-hidden-a','security-hidden-b')$$,'42501',null,'anonymous Explore relationship oracle denied');
select throws_ok($$select public.vault_profiles_blocked('security-hidden-a','security-hidden-b')$$,'42501',null,'anonymous Vault relationship oracle denied');
select throws_ok($$select public.can_access_vault_drop('security-hidden-a','unavailable-drop')$$,'42501',null,'anonymous entitlement probing denied');
select is(public.arena_actor_hidden(null,'security-hidden-b'),false,'guest policy check remains usable');
select throws_ok($$select public.arena_message_room('unknown')$$,'42501',null,'guest private message lookup denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000005101","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.arena_actor_hidden('security-hidden-a','security-hidden-b')$$,'42501',null,'authenticated arbitrary relationship oracle denied');
select throws_ok($$select public.explore_actor_hidden('security-hidden-a','security-hidden-b')$$,'42501',null,'authenticated Explore oracle denied');
select throws_ok($$select public.vault_profiles_blocked('security-hidden-a','security-hidden-b')$$,'42501',null,'authenticated Vault oracle denied');
select throws_ok($$select public.can_access_vault_drop('security-hidden-a','unavailable-drop')$$,'42501',null,'authenticated entitlement probing denied');
select throws_ok($$select public.can_access_course_lesson('security-hidden-a','unavailable-lesson')$$,'42501',null,'course entitlement probing denied');
select throws_ok($$select public.creator_ai_viewer_can_access('unavailable-creator','security-hidden-a')$$,'42501',null,'creator AI entitlement probing denied');
select throws_ok($$select public.creator_live_viewer_can_access('unavailable-session','security-hidden-a')$$,'42501',null,'creator live entitlement probing denied');
select throws_ok($$select public.vault_community_viewer_can_access('security-hidden-a','unavailable-community')$$,'42501',null,'community entitlement probing denied');
select throws_ok($$select public.arena_backup_reasons('security-hidden-a','security-hidden-b','unavailable-topic')$$,'42501',null,'backup relationship builder private');
select throws_ok($$select public.explore_vault_preview_rows('security-hidden-a',null,12)$$,'42501',null,'arbitrary-viewer preview builder private');
select is(public.arena_actor_hidden(public.my_profile_id(),'security-hidden-b'),false,'caller visibility helper remains usable');
select is(public.arena_message_room('unknown'),null::text,'unavailable message reveals no room');
select is(public.arena_evidence_room('unknown'),null::text,'unavailable evidence reveals no room');
reset role;
select * from finish();
rollback;
