begin;
select no_plan();
insert into auth.users(id) values
 ('00000000-0000-0000-0000-000000005201'),('00000000-0000-0000-0000-000000005202'),('00000000-0000-0000-0000-000000005203');
update public.profiles set id='visibility-a',handle='visibility_a' where auth_user_id='00000000-0000-0000-0000-000000005201';
update public.profiles set id='visibility-b',handle='visibility_b' where auth_user_id='00000000-0000-0000-0000-000000005202';
update public.profiles set id='visibility-s',handle='visibility_s' where auth_user_id='00000000-0000-0000-0000-000000005203';
insert into public.takes(id,author_id,hood,text) values('visibility-take','visibility-a','techtakes','Source visibility test');
insert into public.comments(id,take_id,author_id,text) values('visibility-reply','visibility-take','visibility-b','Visible reply');
create temporary table visibility_duel as select public.create_arena_duel('visibility-take','visibility-b','00000000-0000-0000-0000-000000005210') payload;
grant select on visibility_duel to anon,authenticated;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from visibility_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from visibility_duel$$;
create function pg_temp.t() returns text language sql as $$select topic_id from public.arena_rooms where id=pg_temp.r()$$;
create temporary table visibility_topic as select pg_temp.t() id;
grant select on visibility_topic to anon,authenticated;
create or replace function pg_temp.t() returns text language sql as $$select id from visibility_topic$$;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000005201","role":"authenticated"}',true);
select lives_ok($$select public.post_arena_room_message(pg_temp.r(),'Official argument')$$,'fighter transcript still works');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000005203","role":"authenticated"}',true);
select lives_ok($$select public.watch_arena_room(pg_temp.r())$$,'spectator still joins');
select lives_ok($$select public.list_arena_room_messages(pg_temp.r())$$,'spectator reads transcript');
insert into public.blocks(blocker_id,blocked_id) values('visibility-a','visibility-s');
set local role authenticated;
select is((select count(*)::integer from public.takes where id='visibility-take'),0,'reverse block hides direct source');
select is((select count(*)::integer from public.comments where id='visibility-reply'),0,'hidden source hides replies');
select is(public.clash_view(pg_temp.c()),null::jsonb,'legacy Clash RPC hides blocked source');
select is(jsonb_array_length(public.profile_clash_list('visibility-a')),0,'profile Clash list hides blocked source');
select throws_ok($$select public.get_arena_room(pg_temp.r())$$,'42501',null,'canonical Room hides blocked source');
select throws_ok($$select public.list_arena_room_messages(pg_temp.r())$$,'42501',null,'canonical transcript hides blocked source');
reset role;
delete from public.blocks where blocker_id='visibility-a';
update public.takes set status='removed' where id='visibility-take';
set local role anon;
select is((select count(*)::integer from public.takes where id='visibility-take'),0,'anonymous removed source denied');
select is((select count(*)::integer from public.comments where id='visibility-reply'),0,'anonymous replies to removed source denied');
select is(public.clash_view(pg_temp.c()),null::jsonb,'anonymous legacy Clash source denied');
select is(jsonb_array_length(public.profile_clash_list('visibility-a')),0,'anonymous profile Clash source denied');
select is((select count(*)::integer from public.arena_daily_topics where id=pg_temp.t()),0,'copied canonical topic text hidden in direct reads');
select throws_ok($$select public.get_arena_topic(pg_temp.t())$$,'P0002',null,'legacy topic RPC hides removed source copy');
select is((select count(*)::integer from public.list_live_arena_topics() payload where payload->>'id'=pg_temp.t()),0,'live topic listing excludes removed source copy');
reset role;
set local role authenticated;
select is((select count(*)::integer from public.takes where id='visibility-take'),0,'authenticated removed source denied');
select is((select count(*)::integer from public.arena_room_messages where room_id=pg_temp.r()),0,'direct transcript cannot bypass removed source');
select throws_ok($$select public.get_arena_room(pg_temp.r())$$,'42501',null,'removed canonical source denied');
select throws_ok($$select public.get_arena_crowd(pg_temp.r())$$,'42501',null,'Crowd source guard preserved');
reset role;
select * from finish();
rollback;
