begin;
select no_plan();
insert into auth.users(id) values('00000000-0000-0000-0000-000000006601'),('00000000-0000-0000-0000-000000006602');
select ok(not has_table_privilege('anon','public.arena_interest_preferences','select'),'anonymous private reads denied');
select ok(not has_function_privilege('anon','public.save_my_arena_interests(text[],boolean,bigint)','execute'),'anonymous save denied');
select ok(not has_function_privilege('anon','public.get_my_arena_interests()','execute'),'anonymous read RPC denied');
select ok(not has_table_privilege('authenticated','public.arena_interest_preferences','update'),'direct updates denied');
select ok(not has_table_privilege('authenticated','public.arena_interest_preferences','insert'),'direct owner spoofing denied');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006601","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_my_arena_interests()->>'version','0','new account needs onboarding');
select throws_ok($$select public.save_my_arena_interests(array['technology','film'],false,0)$$,'22023',null,'too few');
select throws_ok($$select public.save_my_arena_interests(array['technology','film','sport','gaming','business','education'],false,0)$$,'22023',null,'too many');
select throws_ok($$select public.save_my_arena_interests(array['technology','film','film'],false,0)$$,'22023',null,'duplicates');
select throws_ok($$select public.save_my_arena_interests(array['technology','film','invented'],false,0)$$,'22023',null,'unknown topic');
select throws_ok($$select public.save_my_arena_interests(array['technology','film',null],false,0)$$,'22023',null,'null selection');
select throws_ok($$select public.save_my_arena_interests(array['technology'],true,0)$$,'22023',null,'skip must be explicit zero');
select is(public.save_my_arena_interests(array['technology','film','sport'],false,0)->>'revision','1','first save atomic');
select throws_ok($$select public.save_my_arena_interests(array['business','gaming','education'],false,0)$$,'40001',null,'stale concurrent revision rejected');
select is(jsonb_array_length(public.get_my_arena_interests()->'topicIds'),3,'failed replacement preserves selection');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006602","role":"authenticated"}',true);
set local role authenticated;
select is((select count(*)::integer from public.arena_interest_preferences),0,'other account private row hidden');
select is(public.get_my_arena_interests()->>'version','0','account switch receives own state');
select is(public.save_my_arena_interests('{}',true,0)->>'skipped','true','explicit skip durable');
select is(public.get_my_arena_interests()->>'version','1','skip completes versioned onboarding');
reset role;
select ok((select count(*)>0 from public.arena_interest_preferences where auth_user_id not in ('00000000-0000-0000-0000-000000006601','00000000-0000-0000-0000-000000006602')),'returning users migrated without forced onboarding');
select * from finish();
rollback;
