begin;
select no_plan();
insert into auth.users(id) values
 ('00000000-0000-0000-0000-000000006901'),('00000000-0000-0000-0000-000000006902'),('00000000-0000-0000-0000-000000006903');
update public.profiles set id='inbox-a',handle='inbox_a',name='Inbox recipient' where auth_user_id='00000000-0000-0000-0000-000000006901';
update public.profiles set id='inbox-b',handle='inbox_b',name='Inbox sender' where auth_user_id='00000000-0000-0000-0000-000000006902';
update public.profiles set id='inbox-c',handle='inbox_c',name='Inbox outsider' where auth_user_id='00000000-0000-0000-0000-000000006903';
insert into public.takes(id,author_id,hood,text) select 'inbox-t'||n,'inbox-a','techtakes','Inbox source proposition' from generate_series(1,5) n;
insert into public.arena_challenges(id,take_id,challenger_id,challenged_id,counter_position,created_at,expires_at)
 select ('00000000-0000-0000-0000-00000000691'||n)::uuid,'inbox-t'||n,'inbox-b','inbox-a','A genuine test counter-position with enough text.',
 now()-interval '3 hours',case when n=3 then now()-interval '1 hour' else now()+interval '1 hour' end from generate_series(1,5) n;
update public.takes set is_runtime_fixture=true where id='inbox-t4';
update public.takes set status='removed' where id='inbox-t5';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006901","role":"authenticated"}',true);
set local role authenticated;
select is(public.list_my_arena_challenges('INCOMING')->>'viewerId','inbox-a','caller supplies no owner ID');
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING')->'items'),3,'incoming only visible ordinary sources');
select is(jsonb_array_length(public.list_my_arena_challenges('OUTGOING')->'items'),0,'recipient has no sender records');
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING',null,null,1)->'items'),1,'page size bounded');
select is(public.list_my_arena_challenges('INCOMING',null,null,1)->>'hasMore','true','sentinel indicates next page');
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING',null,null,500)->'items'),3,'oversized request remains bounded');
select throws_ok($$select public.list_my_arena_challenges('EVERYONE')$$,'22023',null,'invalid direction rejected');
select throws_ok($$select public.list_my_arena_challenges('INCOMING',now(),null,20)$$,'22023',null,'partial cursor rejected');
select is((public.list_my_arena_challenges('INCOMING')->'items'->0->'recipient')-array['id','name','handle'],'{}'::jsonb,'recipient whitelist contains no internal fields');
select is((public.list_my_arena_challenges('INCOMING')->'items'->0->'challenger')-array['id','name','handle'],'{}'::jsonb,'challenger whitelist contains no internal fields');
select ok(exists(select 1 from jsonb_array_elements(public.list_my_arena_challenges('INCOMING')->'items') item where item->>'status'='EXPIRED'),'server-derived expiry in read-only inbox');
select is((select count(*)::integer from public.arena_challenges),3,'direct REST-equivalent SELECT also excludes fixtures and removed sources');
select is(jsonb_array_length(public.list_arena_challenges('inbox-t4')),0,'legacy Take list excludes fixtures');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006914','ACCEPT')$$,'42501',null,'direct fixture acceptance refused');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','CANCEL')$$,'42501',null,'recipient cannot cancel');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006902","role":"authenticated"}',true);
set local role authenticated;
select is(jsonb_array_length(public.list_my_arena_challenges('OUTGOING')->'items'),3,'sender sees only own outgoing records');
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING')->'items'),0,'sender cannot read recipient section');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','ACCEPT')$$,'42501',null,'sender cannot accept');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','PASS')$$,'42501',null,'sender cannot decline');
select throws_ok($$select public.create_arena_challenge('inbox-t4','A fixture cannot receive this ordinary invitation.')$$,'P0003',null,'fixture creation refused');
select is(public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','CANCEL')->>'status','CANCELLED','sender cancels own pending invitation');
select is(public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','CANCEL')->>'status','CANCELLED','cancellation retry is idempotent');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006901","role":"authenticated"}',true);
set local role authenticated;
select is(public.resolve_arena_challenge('00000000-0000-0000-0000-000000006912','PASS')->>'status','PASSED','recipient declines');
select is(public.resolve_arena_challenge('00000000-0000-0000-0000-000000006912','PASS')->>'status','PASSED','decline retry is idempotent');
select ok(exists(select 1 from jsonb_array_elements(public.list_my_arena_challenges('INCOMING')->'items') item where item->>'status'='PASSED'),'declined history is visible');
select ok(exists(select 1 from jsonb_array_elements(public.list_my_arena_challenges('INCOMING')->'items') item where item->>'status'='CANCELLED'),'cancelled history is visible');
create temporary table inbox_page as select public.list_my_arena_challenges('INCOMING',null,null,1)->'items'->0 as item;
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING',(select (item->>'createdAt')::timestamptz from inbox_page),(select (item->>'id')::uuid from inbox_page),1)->'items'),1,'keyset next page contains one remaining record');
select isnt(public.list_my_arena_challenges('INCOMING',(select (item->>'createdAt')::timestamptz from inbox_page),(select (item->>'id')::uuid from inbox_page),1)->'items'->0->>'id',(select item->>'id' from inbox_page),'cursor does not duplicate boundary');
reset role;
insert into public.blocks(blocker_id,blocked_id) values('inbox-b','inbox-a');
set local role authenticated;
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING')->'items'),0,'block hides all inbox history');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006912','PASS')$$,'42501',null,'terminal retries revalidate block visibility');
reset role;
delete from public.blocks where blocker_id='inbox-b';
insert into public.mutes(muter_id,muted_id) values('inbox-a','inbox-b');
set local role authenticated;
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING')->'items'),0,'mute hides inbox records');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000006903","role":"authenticated"}',true);
set local role authenticated;
select is(jsonb_array_length(public.list_my_arena_challenges('INCOMING')->'items'),0,'outsider has no incoming records');
select is(jsonb_array_length(public.list_my_arena_challenges('OUTGOING')->'items'),0,'outsider has no outgoing records');
select is((select count(*)::integer from public.arena_challenges),0,'outsider direct table read blocked');
select throws_ok($$select public.resolve_arena_challenge('00000000-0000-0000-0000-000000006911','CANCEL')$$,'42501',null,'outsider cannot act');
select ok(not has_table_privilege('authenticated','public.arena_challenges','UPDATE'),'no direct challenge writes');
select ok(not has_function_privilege('authenticated','public.arena_challenge_payload(public.arena_challenges,boolean)','EXECUTE'),'payload helper remains private');
select ok(not has_function_privilege('anon','public.list_my_arena_challenges(text,timestamptz,uuid,integer)','EXECUTE'),'anonymous inbox denied');
select ok(not has_function_privilege('service_role','public.list_my_arena_challenges(text,timestamptz,uuid,integer)','EXECUTE'),'inbox caller grant remains narrow');
reset role;
select * from finish();
rollback;
