begin;
select no_plan();
insert into auth.users(id) values ('00000000-0000-0000-0000-00000000a701'),('00000000-0000-0000-0000-00000000a702'),('00000000-0000-0000-0000-00000000a703'),('00000000-0000-0000-0000-00000000a704');
update profiles set id='authz-1',handle='authz_1',name='Authorization test 1' where auth_user_id='00000000-0000-0000-0000-00000000a701';
update profiles set id='authz-2',handle='authz_2',name='Authorization test 2' where auth_user_id='00000000-0000-0000-0000-00000000a702';
update profiles set id='authz-3',handle='authz_3',name='Authorization test 3' where auth_user_id='00000000-0000-0000-0000-00000000a703';
update profiles set id='authz-4',handle='authz_4',name='Authorization test 4' where auth_user_id='00000000-0000-0000-0000-00000000a704';
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('authz-take','authz-1','techtakes','Authorization test proposition',true);
create temporary table authz_duel as select create_arena_duel('authz-take','authz-2','00000000-0000-0000-0000-00000000a710') payload;
grant select on authz_duel to authenticated;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from authz_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from authz_duel$$;
insert into arena_daily_topics(id,title,status,opens_at,final_arguments_at,judging_at,closes_at) values('authz-group-topic','Authorization legacy group','live',now()-interval '1 hour',now()+interval '20 minutes',now()+interval '25 minutes',now()+interval '30 minutes');
insert into arena_rooms(id,topic_id,capacity,opens_at,closes_at) values('authz-group','authz-group-topic',40,now()-interval '1 hour',now()+interval '30 minutes');
insert into arena_room_participants(room_id,topic_id,profile_id,initial_stance,role) values('authz-group','authz-group-topic','authz-1','AGREE','debater');
insert into arena_room_messages(id,room_id,author_id,kind,body,media_url,media_kind,gif_provider,gif_external_id) values('authz-gif','authz-group','authz-1','gif','Group gif','https://media.tenor.com/test/tenor.gif','gif','tenor','test');
select ok(not has_function_privilege('authenticated','public.assert_canonical_clash_access(text,boolean)','execute'),'private helper not an identity oracle');
select ok(not has_function_privilege('anon','public.assert_canonical_clash_access(text,boolean)','execute'),'anonymous helper denied');
select ok(not has_function_privilege('service_role','public.assert_canonical_clash_access(text,boolean)','execute'),'helper owner only');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select watch_arena_room(pg_temp.r())$test$,'visible new spectator may join');
select lives_ok($test$select watch_arena_room(pg_temp.r())$test$,'existing member retry retains membership');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select post_arena_room_message(pg_temp.r(),'Visible argument')$test$,'visible fighter post succeeds');
select lives_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Visible evidence','https://example.com/evidence')$test$,'visible evidence succeeds');
select lives_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'visible reshare succeeds');
reset role;
update takes set status='removed' where id='authz-take';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Removed source')$test$,'42501',null,'removed source text denied by known ID');
select throws_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Removed evidence','https://example.com/evidence')$test$,'42501',null,'removed source evidence denied by known ID');
select throws_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'42501',null,'removed source reshare denied by known ID');
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'removed source fighter metadata denied by known ID');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'removed source existing spectator denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a704","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'removed source new spectator denied');
reset role;
select is((select count(*)::int from arena_room_participants where room_id=pg_temp.r()),3,'denial creates no membership');
select lives_ok($test$update arena_room_messages set hidden_at=now() where room_id=pg_temp.r()$test$,'trusted moderation survives removed source');
update takes set status='active' where id='authz-take';
insert into blocks(blocker_id,blocked_id) values('authz-1','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'blocks forward denies fighter 1');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a702","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'blocks forward denies fighter 2');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Unsafe evidence','https://example.com/evidence')$test$,'42501',null,'blocks evidence denied');
select throws_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'42501',null,'blocks reshare denied');
reset role;
delete from blocks where (blocker_id,blocked_id) in (('authz-1','authz-2'),('authz-2','authz-1'));
insert into blocks(blocker_id,blocked_id) values('authz-2','authz-1');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'blocks reverse denies fighter 1');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a702","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'blocks reverse denies fighter 2');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Unsafe evidence','https://example.com/evidence')$test$,'42501',null,'blocks evidence denied');
select throws_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'42501',null,'blocks reshare denied');
reset role;
delete from blocks where (blocker_id,blocked_id) in (('authz-1','authz-2'),('authz-2','authz-1'));
insert into mutes(muter_id,muted_id) values('authz-1','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'mutes forward denies fighter 1');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a702","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'mutes forward denies fighter 2');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Unsafe evidence','https://example.com/evidence')$test$,'42501',null,'mutes evidence denied');
select throws_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'42501',null,'mutes reshare denied');
reset role;
delete from mutes where (muter_id,muted_id) in (('authz-1','authz-2'),('authz-2','authz-1'));
insert into mutes(muter_id,muted_id) values('authz-2','authz-1');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'mutes reverse denies fighter 1');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a702","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select post_arena_room_message(pg_temp.r(),'Unsafe fighter argument')$test$,'42501',null,'mutes reverse denies fighter 2');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_arena_evidence(pg_temp.r(),'link','Unsafe evidence','https://example.com/evidence')$test$,'42501',null,'mutes evidence denied');
select throws_ok($test$select post_arena_clash_media_reshare(pg_temp.r(),'authz-gif')$test$,'42501',null,'mutes reshare denied');
reset role;
delete from mutes where (muter_id,muted_id) in (('authz-1','authz-2'),('authz-2','authz-1'));
insert into blocks(blocker_id,blocked_id) values('authz-3','authz-1'),('authz-4','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'blocks existing spectator denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a704","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'blocks new spectator denied');
reset role;
delete from blocks where blocker_id in('authz-3','authz-4');
insert into mutes(muter_id,muted_id) values('authz-3','authz-1'),('authz-4','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'mutes existing spectator denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a704","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select watch_arena_room(pg_temp.r())$test$,'42501',null,'mutes new spectator denied');
reset role;
delete from mutes where muter_id in('authz-3','authz-4');
update clashes set opens_at=now()-interval '26 minutes',closes_at=now()+interval '4 minutes' where id=pg_temp.c();
update arena_rooms set opens_at=now()-interval '26 minutes',closes_at=now()+interval '4 minutes',status='JUDGING' where id=pg_temp.r();
update arena_daily_topics set opens_at=now()-interval '26 minutes',final_arguments_at=now()-interval '6 minutes',judging_at=now()-interval '1 minute',closes_at=now()+interval '4 minutes' where id=(select topic_id from arena_rooms where id=pg_temp.r());
update takes set status='removed' where id='authz-take';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_judgement(pg_temp.c(),'A')$test$,'42501',null,'removed source known-ID ballot denied');
reset role;
update takes set status='active' where id='authz-take';
insert into blocks(blocker_id,blocked_id) values('authz-3','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_judgement(pg_temp.c(),'A')$test$,'42501',null,'blocks known-ID ballot denied');
reset role;
delete from blocks where blocker_id='authz-3';
insert into mutes(muter_id,muted_id) values('authz-3','authz-2');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($test$select submit_judgement(pg_temp.c(),'A')$test$,'42501',null,'mutes known-ID ballot denied');
reset role;
delete from mutes where muter_id='authz-3';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a704","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select submit_judgement(pg_temp.c(),'A')$test$,'public authenticated nonmember judging unchanged');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select post_arena_room_message('authz-group','Legacy group unaffected')$test$,'GROUP publishing unaffected');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a704","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select watch_arena_room('authz-group')$test$,'GROUP watch unaffected');
reset role;
-- Historical permissions and Crowd policy remain separate from watch access.
update clashes set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=pg_temp.c();
update arena_rooms set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=pg_temp.r();
update arena_daily_topics set opens_at=now()-interval '31 minutes',final_arguments_at=now()-interval '11 minutes',judging_at=now()-interval '6 minutes',closes_at=now()-interval '1 minute' where id=(select topic_id from arena_rooms where id=pg_temp.r());
select lives_ok($test$select settle_clash(pg_temp.c())$test$,'existing verdict settlement unchanged');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select watch_arena_room(pg_temp.r())$test$,'existing settled spectator retains Stage access');
select is(get_arena_crowd(pg_temp.r())->>'canSend','false','settled Crowd stays read only');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select watch_arena_room(pg_temp.r())$test$,'settled fighter metadata remains available');
reset role;
select set_config('request.jwt.claims',null,true);
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('authz-cancel-take','authz-1','techtakes','Authorization cancellation fixture',true);
create temporary table authz_cancel as select create_arena_duel('authz-cancel-take','authz-2','00000000-0000-0000-0000-00000000a721') payload;
grant select on authz_cancel to authenticated;
update clashes set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=(select payload->>'clashId' from authz_cancel);
update arena_rooms set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=(select payload->>'roomId' from authz_cancel);
update arena_daily_topics set opens_at=now()-interval '31 minutes',final_arguments_at=now()-interval '11 minutes',judging_at=now()-interval '6 minutes',closes_at=now()-interval '1 minute' where id=(select topic_id from arena_rooms where id=(select payload->>'roomId' from authz_cancel));
select is(settle_clash((select payload->>'clashId' from authz_cancel))->>'status','cancelled','zero ballots still cancel without invented verdict');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($test$select list_arena_room_messages((select payload->>'roomId' from authz_cancel))$test$,'cancelled fighter can read historical Stage');
select throws_ok($test$select get_arena_crowd((select payload->>'roomId' from authz_cancel))$test$,'42501',null,'cancelled Crowd still denied to fighter');
reset role;
select lives_ok('set constraints all immediate','canonical graph remains intact');
select * from finish();
rollback;
