begin;
select no_plan();
insert into auth.users(id) values ('00000000-0000-0000-0000-00000000a701'),('00000000-0000-0000-0000-00000000a702'),('00000000-0000-0000-0000-00000000a703'),('00000000-0000-0000-0000-00000000a704');
update profiles set id='authz-1',handle='authz_1',name='Authorization test 1' where auth_user_id='00000000-0000-0000-0000-00000000a701';
update profiles set id='authz-2',handle='authz_2',name='Authorization test 2' where auth_user_id='00000000-0000-0000-0000-00000000a702';
update profiles set id='authz-3',handle='authz_3',name='Authorization test 3' where auth_user_id='00000000-0000-0000-0000-00000000a703';
update profiles set id='authz-4',handle='authz_4',name='Authorization test 4' where auth_user_id='00000000-0000-0000-0000-00000000a704';
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('authz-take','authz-1','techtakes','Authorization test proposition',true);
create temporary table authz_duel as select create_arena_duel('authz-take','authz-2','00000000-0000-0000-0000-00000000a710') payload;
grant select on authz_duel to authenticated;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from authz_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from authz_duel$$;
insert into arena_daily_topics(id,title,status,opens_at,final_arguments_at,judging_at,closes_at) values('authz-group-topic','Authorization legacy group','live',now()-interval '1 hour',now()+interval '20 minutes',now()+interval '25 minutes',now()+interval '30 minutes');
insert into arena_rooms(id,topic_id,capacity,opens_at,closes_at) values('authz-group','authz-group-topic',40,now()-interval '1 hour',now()+interval '30 minutes');
insert into arena_room_participants(room_id,topic_id,profile_id,initial_stance,role) values('authz-group','authz-group-topic','authz-1','AGREE','debater');
insert into arena_room_messages(id,room_id,author_id,kind,body,media_url,media_kind,gif_provider,gif_external_id) values('authz-gif','authz-group','authz-1','gif','Group gif','https://media.tenor.com/test/tenor.gif','gif','tenor','test');
select ok(not has_table_privilege('authenticated','arena_official_requests','select'),'receipts are private');
select ok(not has_function_privilege('anon','submit_arena_official(text,text,jsonb,uuid)','execute'),'anonymous submissions denied');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
create temporary table recovery_sent as select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701') payload;
select is(submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')->>'id',(select payload->>'id' from recovery_sent),'lost-response retry returns original message');
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Changed"}','00000000-0000-0000-0000-00000000b701')$$,'P0006',null,'changed same-key payload denied');
create temporary table recovery_evidence as select submit_arena_official(pg_temp.r(),'evidence','{"kind":"link","title":"Reliable proof","sourceUrl":"https://example.com/proof"}','00000000-0000-0000-0000-00000000b702') payload;
select is(submit_arena_official(pg_temp.r(),'evidence','{"kind":"link","title":"Reliable proof","sourceUrl":"https://example.com/proof"}','00000000-0000-0000-0000-00000000b702')->>'id',(select payload->>'id' from recovery_evidence),'evidence retry returns original');
create temporary table recovery_reshare as select submit_arena_official(pg_temp.r(),'reshare','{"sourceMessageId":"authz-gif"}','00000000-0000-0000-0000-00000000b703') payload;
select is(submit_arena_official(pg_temp.r(),'reshare','{"sourceMessageId":"authz-gif"}','00000000-0000-0000-0000-00000000b703')->>'id',(select payload->>'id' from recovery_reshare),'reshare retry returns original');
select throws_ok($$select submit_arena_official(pg_temp.r(),'evidence','{"kind":"link","title":"Changed proof","sourceUrl":"https://example.com/proof"}','00000000-0000-0000-0000-00000000b702')$$,'P0006',null,'changed evidence payload rejected');
select throws_ok($$select submit_arena_official(pg_temp.r(),'reshare','{"sourceMessageId":"authz-gif","body":"Changed caption"}','00000000-0000-0000-0000-00000000b703')$$,'P0006',null,'changed reshare payload rejected');
select throws_ok($$select submit_arena_official(pg_temp.r(),'reshare','{"sourceMessageId":"authz-gif"}','00000000-0000-0000-0000-00000000b701')$$,'P0006',null,'operation cannot reuse another request key');
reset role;
select is((select count(*)::int from arena_room_messages where room_id=pg_temp.r()),2,'retries do not duplicate official messages');
select is((select count(*)::int from rate_limit_events where actor_id='authz-1' and action='arena_room_message'),2,'message and reshare retries charge quota once');
select is((select count(*)::int from arena_room_evidence where room_id=pg_temp.r()),1,'retry does not duplicate evidence');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a702","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')$$,'42501',null,'other fighter cannot reuse request key');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Spectator"}','00000000-0000-0000-0000-00000000b704')$$,'42501',null,'spectator cannot use new official endpoint');
select throws_ok($$select list_arena_official_page(pg_temp.r())$$,'42501',null,'nonmember page denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
update takes set status='removed' where id='authz-take';
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')$$,'42501',null,'removed source retry denied');
reset role;
update takes set status='active' where id='authz-take';
insert into blocks(blocker_id,blocked_id) values('authz-2','authz-1');
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')$$,'42501',null,'blocks invalidates retry access');
reset role;
delete from blocks where (blocker_id,blocked_id)=('authz-2','authz-1');
insert into mutes(muter_id,muted_id) values('authz-2','authz-1');
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')$$,'42501',null,'mutes invalidates retry access');
reset role;
delete from mutes where (muter_id,muted_id)=('authz-2','authz-1');
update arena_room_messages set hidden_at=now() where id=(select payload->>'id' from recovery_sent);
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')$$,'42501',null,'hidden retry does not resurrect content');
reset role;
update arena_room_messages set hidden_at=null where id=(select payload->>'id' from recovery_sent);
insert into arena_room_messages(id,room_id,author_id,body,created_at,parent_message_id)
 select 'rc_'||lpad(n::text,4,'0'),pg_temp.r(),'authz-1','Equal timestamp argument',date_trunc('second',now())+interval '1 minute 1 microsecond',case when n>1 then 'rc_0001' end from generate_series(1,100) n;
insert into arena_room_evidence(id,room_id,topic_id,author_id,kind,title,source_url,created_at)
 select 're_'||lpad(n::text,4,'0'),r.id,r.topic_id,'authz-1','link','Equal timestamp proof','https://example.com/proof',date_trunc('second',now())+interval '1 minute 1 microsecond' from arena_rooms r cross join generate_series(1,100) n where r.id=pg_temp.r();
-- Trusted fixture timestamp adjustment; production inserts use server admission time.
update arena_room_messages set created_at=date_trunc('second',now())+interval '1 minute 1 microsecond' where room_id=pg_temp.r() and id like 'rc_%';
update arena_room_evidence set created_at=date_trunc('second',now())+interval '1 minute 1 microsecond' where room_id=pg_temp.r() and id like 're_%';
set local role authenticated;
create temporary table recovery_first as select list_arena_official_page(pg_temp.r(),'message',now()+interval '30 seconds','~','newer',40) payload;
create temporary table recovery_second as select list_arena_official_page(pg_temp.r(),'message',(select (payload->39->>'createdAt')::timestamptz from recovery_first),(select payload->39->>'id' from recovery_first),'newer',40) payload;
create temporary table recovery_third as select list_arena_official_page(pg_temp.r(),'message',(select (payload->39->>'createdAt')::timestamptz from recovery_second),(select payload->39->>'id' from recovery_second),'newer',40) payload;
select is(jsonb_array_length((select payload from recovery_first)),40,'first reconnect batch bounded');
select is(jsonb_array_length((select payload from recovery_second)),40,'equal timestamp gap exceeds 40');
select is(jsonb_array_length((select payload from recovery_third)),20,'equal timestamp gap exceeds 80 recovered fully');
select is((select payload->0->>'id' from recovery_second),'rc_0041','unique ID cursor prevents equal timestamp skips');
select is((select payload->0->>'parentMessageId' from recovery_second),'rc_0001','reply parent identity preserved');
select is((select (payload->0->>'createdAt')::timestamptz from recovery_first),date_trunc('second',now())+interval '1 minute 1 microsecond','PostgreSQL microseconds preserved');
select is(jsonb_array_length(list_arena_official_page(pg_temp.r(),'evidence',now()+interval '30 seconds','~','newer',100)),100,'all equal timestamp evidence retrieved');
select throws_ok($$select list_arena_official_page(pg_temp.r(),'message',now(),null)$$,'22023',null,'partial cursor rejected');
select throws_ok($$select list_arena_official_page(pg_temp.r(),'message',null,null,'older',101)$$,'22023',null,'page cap enforced');
select lives_ok($$select list_arena_official_page('authz-group')$$,'legacy GROUP page compatible');
select lives_ok($$select post_arena_room_message('authz-group','Legacy caller remains valid')$$,'old posting signature unaffected');
reset role;
update clashes set opens_at=now()-interval '26 minutes',closes_at=now()+interval '4 minutes' where id=pg_temp.c();
update arena_rooms set opens_at=now()-interval '26 minutes',closes_at=now()+interval '4 minutes' where id=pg_temp.r();
update arena_daily_topics set opens_at=now()-interval '26 minutes',closes_at=now()+interval '4 minutes',judging_at=now()-interval '1 minute',final_arguments_at=now()-interval '2 minutes' where id=(select topic_id from arena_rooms where id=pg_temp.r());
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"New late argument"}','00000000-0000-0000-0000-00000000b705')$$,'P0003',null,'new request cannot bypass official deadline');
select is(submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')->>'id',(select payload->>'id' from recovery_sent),'closed-window retry acknowledges existing row without writing');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a703","role":"authenticated"}',true);
select submit_judgement(pg_temp.c(),'A');
update clashes set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=pg_temp.c();
update arena_rooms set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=pg_temp.r();
update arena_daily_topics set opens_at=now()-interval '31 minutes',final_arguments_at=now()-interval '11 minutes',judging_at=now()-interval '6 minutes',closes_at=now()-interval '1 minute' where id=(select topic_id from arena_rooms where id=pg_temp.r());
select settle_clash(pg_temp.c());
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a701","role":"authenticated"}',true);
set local role authenticated;
select is(submit_arena_official(pg_temp.r(),'message','{"body":"Reliable argument"}','00000000-0000-0000-0000-00000000b701')->>'id',(select payload->>'id' from recovery_sent),'settled retry is a read-only acknowledgement');
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"New settled argument"}','00000000-0000-0000-0000-00000000b707')$$,'P0003',null,'settled Room denies new request');
select lives_ok($$select list_arena_official_page(pg_temp.r())$$,'settled history remains readable to member');
reset role;
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('retry-cancel-take','authz-1','techtakes','Retry cancellation fixture',true);
create temporary table retry_cancel as select create_arena_duel('retry-cancel-take','authz-2','00000000-0000-0000-0000-00000000b708') payload;
grant select on retry_cancel to authenticated;
select submit_arena_official((select payload->>'roomId' from retry_cancel),'message','{"body":"Before cancellation"}','00000000-0000-0000-0000-00000000b709');
update clashes set status='cancelled' where id=(select payload->>'clashId' from retry_cancel);
update arena_rooms set status='CANCELLED' where id=(select payload->>'roomId' from retry_cancel);
set local role authenticated;
select lives_ok($$select list_arena_official_page((select payload->>'roomId' from retry_cancel))$$,'cancelled member historical Stage remains readable');
select throws_ok($$select submit_arena_official((select payload->>'roomId' from retry_cancel),'message','{"body":"Before cancellation"}','00000000-0000-0000-0000-00000000b709')$$,'42501',null,'cancelled request endpoint denies even retries');
reset role;
select lives_ok('set constraints all immediate','retry graph invariants intact');
select * from finish();
rollback;
