begin;
select no_plan();
create extension if not exists dblink with schema extensions;
select extensions.dblink_connect('az-one','host=127.0.0.1 port=5432 user=postgres password=postgres dbname='||current_database());
select extensions.dblink_connect('az-two','host=127.0.0.1 port=5432 user=postgres password=postgres dbname='||current_database());
select extensions.dblink_exec('az-one',$remote$
do $fixture$ begin
 delete from takes where id='authz-race-take';
 delete from arena_daily_topics where title='Authorization race fixture';
 delete from profiles where id in('az-race-a','az-race-b','az-race-s');
 delete from auth.users where id in('00000000-0000-0000-0000-00000000a711','00000000-0000-0000-0000-00000000a712','00000000-0000-0000-0000-00000000a713');
 insert into auth.users(id) values('00000000-0000-0000-0000-00000000a711'),('00000000-0000-0000-0000-00000000a712'),('00000000-0000-0000-0000-00000000a713');
 update profiles set id='az-race-a',handle='az_race_a',name='Race A' where auth_user_id='00000000-0000-0000-0000-00000000a711';
 update profiles set id='az-race-b',handle='az_race_b',name='Race B' where auth_user_id='00000000-0000-0000-0000-00000000a712';
 update profiles set id='az-race-s',handle='az_race_s',name='Race spectator' where auth_user_id='00000000-0000-0000-0000-00000000a713';
 insert into takes(id,author_id,hood,text,is_runtime_fixture) values('authz-race-take','az-race-a','techtakes','Authorization race fixture',true);
 perform create_arena_duel('authz-race-take','az-race-b','00000000-0000-0000-0000-00000000a720');
end $fixture$;
$remote$);
select * from extensions.dblink('az-one',$remote$select set_config('az.room',r.id,false) from arena_rooms r join clashes c on c.id=r.clash_id where c.take_id='authz-race-take'$remote$) as x(setting text);
select * from extensions.dblink('az-two',$remote$select set_config('az.room',r.id,false) from arena_rooms r join clashes c on c.id=r.clash_id where c.take_id='authz-race-take'$remote$) as x(setting text);
select * from extensions.dblink('az-one',$remote$select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a711","role":"authenticated"}',false)$remote$) as x(claims text);
select extensions.dblink_exec('az-one','set role authenticated');
select * from extensions.dblink('az-two',$remote$select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a711","role":"authenticated"}',false)$remote$) as x(claims text);
select extensions.dblink_exec('az-two','set role authenticated');
select extensions.dblink_exec('az-one','begin');
create temporary table official_first as select payload from extensions.dblink('az-one',$remote$select submit_arena_official(current_setting('az.room'),'message','{"body":"Concurrent official request"}','00000000-0000-0000-0000-00000000b711')$remote$) as x(payload jsonb);
select is(extensions.dblink_send_query('az-two',$remote$select submit_arena_official(current_setting('az.room'),'message','{"body":"Concurrent official request"}','00000000-0000-0000-0000-00000000b711')$remote$),1,'concurrent same-key official submission queued');
select pg_sleep(0.1);
select is(extensions.dblink_is_busy('az-two'),1,'same key waits on original transaction');
select extensions.dblink_exec('az-one','commit');
create temporary table official_retry as select payload from extensions.dblink_get_result('az-two') as x(payload jsonb);
select * from extensions.dblink_get_result('az-two') as x(payload jsonb);
select is((select payload->>'id' from official_retry),(select payload->>'id' from official_first),'concurrent retry resolves to original ID');
select is((select count(*)::int from arena_room_messages where author_id='az-race-a'),1,'concurrent same-key creates one official row');
select is((select count(*)::int from rate_limit_events where actor_id='az-race-a' and action='arena_room_message'),1,'concurrent retry consumes quota once');
select is((select count(*)::int from arena_official_requests where author_id='az-race-a'),1,'one committed receipt');
select extensions.dblink_exec('az-one','begin');
create temporary table race_evidence_first as select payload from extensions.dblink('az-one',$remote$select submit_arena_official(current_setting('az.room'),'evidence','{"kind":"link","title":"Concurrent proof","sourceUrl":"https://example.com/proof"}','00000000-0000-0000-0000-00000000b712')$remote$) as x(payload jsonb);
select is(extensions.dblink_send_query('az-two',$remote$select submit_arena_official(current_setting('az.room'),'evidence','{"kind":"link","title":"Concurrent proof","sourceUrl":"https://example.com/proof"}','00000000-0000-0000-0000-00000000b712')$remote$),1,'evidence retry starts concurrently');
select pg_sleep(0.1);
select is(extensions.dblink_is_busy('az-two'),1,'evidence retry waits on original commit');
select extensions.dblink_exec('az-one','commit');
create temporary table race_evidence_retry as select payload from extensions.dblink_get_result('az-two') as x(payload jsonb);
select * from extensions.dblink_get_result('az-two') as x(payload jsonb);
select is((select payload->>'id' from race_evidence_retry),(select payload->>'id' from race_evidence_first),'evidence race returns one authoritative contribution');
create temporary table race_gif as select id from extensions.dblink('az-one',$remote$select id from post_arena_room_message(current_setting('az.room'),'GIF source',null,null,'https://media.tenor.com/test/tenor.gif','tenor','test')$remote$) as x(id text);
select extensions.dblink_exec('az-one','begin');
create temporary table race_reshare_first as select payload from extensions.dblink('az-one',format('select submit_arena_official(current_setting(''az.room''),''reshare'',%L::jsonb,''00000000-0000-0000-0000-00000000b713'')',jsonb_build_object('sourceMessageId',(select id from race_gif))::text)) as x(payload jsonb);
select is(extensions.dblink_send_query('az-two',format('select submit_arena_official(current_setting(''az.room''),''reshare'',%L::jsonb,''00000000-0000-0000-0000-00000000b713'')',jsonb_build_object('sourceMessageId',(select id from race_gif))::text)),1,'reshare retry starts concurrently');
select pg_sleep(0.1);
select is(extensions.dblink_is_busy('az-two'),1,'reshare retry waits on original commit');
select extensions.dblink_exec('az-one','commit');
create temporary table race_reshare_retry as select payload from extensions.dblink_get_result('az-two') as x(payload jsonb);
select * from extensions.dblink_get_result('az-two') as x(payload jsonb);
select is((select payload->>'id' from race_reshare_retry),(select payload->>'id' from race_reshare_first),'reshare race returns one authoritative contribution');
select extensions.dblink_exec('az-one','reset role');
select extensions.dblink_exec('az-one',$remote$
delete from takes where id='authz-race-take';
delete from arena_daily_topics where title='Authorization race fixture';
delete from rate_limit_events where actor_id in('az-race-a','az-race-b','az-race-s');
delete from profiles where id in('az-race-a','az-race-b','az-race-s');
delete from auth.users where id in('00000000-0000-0000-0000-00000000a711','00000000-0000-0000-0000-00000000a712','00000000-0000-0000-0000-00000000a713');
$remote$);
select extensions.dblink_disconnect('az-one');
select extensions.dblink_disconnect('az-two');
select * from finish();
rollback;
