begin;
select no_plan();
insert into auth.users(id) values ('00000000-0000-0000-0000-00000000a741'),('00000000-0000-0000-0000-00000000a742'),('00000000-0000-0000-0000-00000000a743'),('00000000-0000-0000-0000-00000000a744');
update profiles set id='history-a',handle='history_a' where auth_user_id='00000000-0000-0000-0000-00000000a741';
update profiles set id='history-b',handle='history_b' where auth_user_id='00000000-0000-0000-0000-00000000a742';
update profiles set id='history-j',handle='history_j' where auth_user_id='00000000-0000-0000-0000-00000000a743';
update profiles set id='history-s',handle='history_s' where auth_user_id='00000000-0000-0000-0000-00000000a744';
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('history-take','history-a','techtakes','Historical entry rollback fixture',true);
create temporary table history_duel as select create_arena_duel('history-take','history-b','00000000-0000-0000-0000-00000000a740') payload;
grant select on history_duel to authenticated;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from history_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from history_duel$$;
create function pg_temp.shift_clock(p_close timestamptz) returns void language plpgsql as $$begin
 update clashes set opens_at=p_close-interval '30 minutes',closes_at=p_close where id=pg_temp.c();
 update arena_rooms set opens_at=p_close-interval '30 minutes',closes_at=p_close where id=pg_temp.r();
 update arena_daily_topics set opens_at=p_close-interval '30 minutes',final_arguments_at=p_close-interval '10 minutes',judging_at=p_close-interval '5 minutes',closes_at=p_close where id=(select topic_id from arena_rooms where id=pg_temp.r());
end$$;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a741","role":"authenticated"}',true);
select submit_arena_official(pg_temp.r(),'message','{"body":"An existing official argument"}','00000000-0000-0000-0000-00000000b741');
select pg_temp.shift_clock(now()+interval '2 minutes');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a743","role":"authenticated"}',true);
select submit_judgement(pg_temp.c(),'A');
select pg_temp.shift_clock(now()-interval '1 minute');
select is(settle_clash(pg_temp.c())->>'winner_side','A','one ballot settles with genuine verdict');
update arena_daily_topics set status='closed' where id=(select topic_id from arena_rooms where id=pg_temp.r());
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a744","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select list_arena_official_page(pg_temp.r())$$,'42501',null,'new historical visitor is not implicitly a member');
reset role;
update takes set status='removed' where id='history-take';
set local role authenticated;
select throws_ok($$select watch_arena_room(pg_temp.r())$$,'42501',null,'removed source historical watch denied');
reset role;
update takes set status='active' where id='history-take';
insert into blocks(blocker_id,blocked_id) values('history-a','history-s');
set local role authenticated;
select throws_ok($$select watch_arena_room(pg_temp.r())$$,'42501',null,'blocked new historical spectator denied');
reset role;
delete from blocks where blocker_id='history-a';
insert into mutes(muter_id,muted_id) values('history-s','history-a');
set local role authenticated;
select throws_ok($$select watch_arena_room(pg_temp.r())$$,'42501',null,'muted source historical watch denied');
reset role;
delete from mutes where muter_id='history-s';
set local role authenticated;
select is(watch_arena_room(pg_temp.r())->>'joined','true','new spectator enters readable settled closed-topic Room');
select is(watch_arena_room(pg_temp.r())->>'joined','false','historical watch retry retains one membership');
select is(jsonb_array_length(list_arena_official_page(pg_temp.r())),1,'authorized historical Stage recovers official transcript');
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Spectator attack"}',gen_random_uuid())$$,'42501',null,'historical spectator cannot submit arguments');
select throws_ok($$select submit_judgement(pg_temp.c(),'B')$$,'P0003',null,'settled historical entry cannot reopen judging');
select throws_ok($$select post_arena_crowd_message(pg_temp.r(),'After close',gen_random_uuid())$$,'P0003',null,'settled Crowd is read-only');
reset role;
select is((select count(*)::int from arena_room_participants where room_id=pg_temp.r() and role='spectator'),1,'no duplicate historical membership');
select is((select count(*)::int from arena_room_participants where room_id=pg_temp.r() and role='debater'),2,'historical entry preserves exactly two fighters');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a741","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select submit_arena_official(pg_temp.r(),'message','{"body":"Late fighter attack"}',gen_random_uuid())$$,'P0003',null,'settled fighter cannot create new official argument');
reset role;
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('history-cancel-take','history-a','techtakes','Cancelled history rollback fixture',true);
create temporary table history_cancel as select create_arena_duel('history-cancel-take','history-b','00000000-0000-0000-0000-00000000b740') payload;
grant select on history_cancel to authenticated;
update clashes set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=(select payload->>'clashId' from history_cancel);
update arena_rooms set opens_at=now()-interval '31 minutes',closes_at=now()-interval '1 minute' where id=(select payload->>'roomId' from history_cancel);
update arena_daily_topics set opens_at=now()-interval '31 minutes',final_arguments_at=now()-interval '11 minutes',judging_at=now()-interval '6 minutes',closes_at=now()-interval '1 minute' where id=(select topic_id from arena_rooms where id=(select payload->>'roomId' from history_cancel));
select is(settle_clash((select payload->>'clashId' from history_cancel))->>'status','cancelled','zero ballots cancel without a verdict');
select is(settle_clash((select payload->>'clashId' from history_cancel))->>'status','cancelled','cancelled settlement retry succeeds');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a744","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select watch_arena_room((select payload->>'roomId' from history_cancel))$$,'P0003',null,'cancelled Room refuses new spectators');
select throws_ok($$select list_arena_official_page((select payload->>'roomId' from history_cancel))$$,'42501',null,'cancelled outsider cannot read transcript');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a741","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select list_arena_official_page((select payload->>'roomId' from history_cancel))$$,'cancelled existing fighter retains Stage history');
select throws_ok($$select get_arena_crowd((select payload->>'roomId' from history_cancel))$$,'42501',null,'cancelled Crowd denied to existing fighter');
reset role;
select lives_ok('set constraints all immediate','historical terminal graphs remain valid');
select * from finish();
rollback;
