begin;
select no_plan();
select ok(not has_table_privilege('anon','arena_maintenance_failures','select'),'anonymous diagnostics denied');
select ok(not has_table_privilege('authenticated','arena_maintenance_failures','select'),'ordinary diagnostics denied');
select ok(has_table_privilege('service_role','arena_maintenance_failures','select'),'operators can inspect diagnostics');
select ok(not has_function_privilege('authenticated','record_arena_maintenance_failure(text,text,text)','execute'),'client cannot forge failure diagnostics');
select ok(not has_function_privilege('authenticated','resolve_arena_maintenance_failure(text,text)','execute'),'client cannot hide failure diagnostics');
select ok(not has_function_privilege('authenticated','run_maintenance(integer)','execute'),'client cannot invoke maintenance');
select ok(not has_function_privilege('anon','settle_due_clashes(integer)','execute'),'anonymous batch denied');
select ok(not has_function_privilege('authenticated','transition_due_arena_rooms(integer)','execute'),'client phase batch denied');
set local role anon;
select throws_ok('select * from arena_maintenance_failures','42501',null,'direct anonymous diagnostic read denied');
reset role;
set local role authenticated;
select throws_ok('select * from arena_maintenance_failures','42501',null,'direct authenticated diagnostic read denied');
select throws_ok($$select record_arena_maintenance_failure('clash_settlement','known-id','P0001')$$,'42501',null,'known-ID diagnostic forgery RPC denied');
select throws_ok($$select resolve_arena_maintenance_failure('clash_settlement','known-id')$$,'42501',null,'known-ID diagnostic resolution RPC denied');
select throws_ok('select run_maintenance(500)','42501',null,'direct authenticated maintenance RPC denied');
reset role;
insert into auth.users(id) values ('00000000-0000-0000-0000-00000000a751'),('00000000-0000-0000-0000-00000000a752'),('00000000-0000-0000-0000-00000000a753');
update profiles set id='recovery-a',handle='recovery_a' where auth_user_id='00000000-0000-0000-0000-00000000a751';
update profiles set id='recovery-b',handle='recovery_b' where auth_user_id='00000000-0000-0000-0000-00000000a752';
update profiles set id='recovery-j',handle='recovery_j' where auth_user_id='00000000-0000-0000-0000-00000000a753';
insert into takes(id,author_id,hood,text,is_runtime_fixture) values('recovery-take','recovery-a','techtakes','Maintenance rollback fixture',true);
create temporary table recovery_duel as select create_arena_duel('recovery-take','recovery-b','00000000-0000-0000-0000-00000000b750') payload;
create function pg_temp.r() returns text language sql as $$select payload->>'roomId' from recovery_duel$$;
create function pg_temp.c() returns text language sql as $$select payload->>'clashId' from recovery_duel$$;
update clashes set opens_at=now()-interval '28 minutes',closes_at=now()+interval '2 minutes' where id=pg_temp.c();
update arena_rooms set opens_at=now()-interval '28 minutes',closes_at=now()+interval '2 minutes' where id=pg_temp.r();
update arena_daily_topics set opens_at=now()-interval '28 minutes',final_arguments_at=now()-interval '8 minutes',judging_at=now()-interval '3 minutes',closes_at=now()+interval '2 minutes' where id=(select topic_id from arena_rooms where id=pg_temp.r());
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a753","role":"authenticated"}',true);
select submit_judgement(pg_temp.c(),'A');
select set_config('request.jwt.claims',null,true);
update clashes set closes_at=now()-interval '1 minute' where id=pg_temp.c();
update arena_rooms set closes_at=now()-interval '1 minute' where id=pg_temp.r();
update arena_daily_topics set closes_at=now()-interval '1 minute' where id=(select topic_id from arena_rooms where id=pg_temp.r());
create temporary table recovery_original as select reputation,coins,streak from profiles where id='recovery-j';
-- Fail after verdict insertion and reputation updates, at the notification seam.
create function pg_temp.fail_result_notification() returns trigger language plpgsql as $$begin
 if new.entity_id=pg_temp.c() then raise exception 'secret private profile relationship' using errcode='23514',detail='sensitive room body'; end if;
 return new;
end$$;
create trigger recovery_failure before insert on notifications for each row execute function pg_temp.fail_result_notification();
create temporary table failed_run as select run_maintenance(500) result;
select is((select result->>'partial_failure' from failed_run),'true','maintenance truthfully reports partial failure');
select cmp_ok((select (result->>'maintenance_item_failures')::int from failed_run),'>=',2,'both settlement and Room transition failure counted');
select is((select status::text from clashes where id=pg_temp.c()),'open','failed settlement leaves server pending');
select is((select count(*)::int from verdicts where clash_id=pg_temp.c()),0,'failure rolls back inserted verdict');
select is((select count(*)::int from reputation_events where clash_id=pg_temp.c()),0,'failure rolls back reward ledger');
select is((select count(*)::int from notifications where entity_id=pg_temp.c()),0,'failure rolls back notifications');
select ok((select (p.reputation,p.coins,p.streak)=(o.reputation,o.coins,o.streak) from profiles p cross join recovery_original o where p.id='recovery-j'),'failure rolls back profile award');
select is((select count(*)::int from arena_maintenance_failures where item_id in(pg_temp.c(),pg_temp.r()) and retry_status='pending'),2,'both failed operations retained for operators');
select is((select sqlstate from arena_maintenance_failures where item_id=pg_temp.c()),'23514','diagnostic retains safe SQLSTATE');
select is((select safe_detail from arena_maintenance_failures where item_id=pg_temp.c()),'Integrity constraint failure','diagnostic excludes raw private message and detail');
select ok((select first_failed_at is not null and last_failed_at>=first_failed_at from arena_maintenance_failures where item_id=pg_temp.c()),'diagnostics retain genuine server timestamps');
select run_maintenance(500);
select is((select failed_attempts from arena_maintenance_failures where item_id=pg_temp.c()),2,'repeated failure increments retry count');
drop trigger recovery_failure on notifications;
create temporary table recovered_run as select run_maintenance(500) result;
select is((select result->>'partial_failure' from recovered_run),'false','recovery reports no new item failures');
select is((select status::text from clashes where id=pg_temp.c()),'settled','next existing maintenance run settles failed Clash');
select is((select status::text from arena_rooms where id=pg_temp.r()),'SETTLED','recovery reaches coherent terminal Room');
select is((select count(*)::int from verdicts where clash_id=pg_temp.c()),1,'one verdict after recovery');
select is((select count(*)::int from reputation_events where clash_id=pg_temp.c()),2,'one participation and win award after recovery');
select is((select count(*)::int from notifications where entity_id=pg_temp.c()),3,'one juror and two fighter notifications after recovery');
select is((select p.reputation-o.reputation from profiles p cross join recovery_original o where id='recovery-j'),120,'one winning jury reputation award');
select is((select count(*)::int from arena_maintenance_failures where item_id in(pg_temp.c(),pg_temp.r()) and retry_status='resolved' and resolved_at is not null),2,'terminal recovery resolves both diagnostic categories');
select is(settle_clash(pg_temp.c())->>'winner_side','A','direct settled retry returns original verdict');
select run_maintenance(500);
select is((select count(*)::int from reputation_events where clash_id=pg_temp.c()),2,'maintenance and direct retries do not duplicate awards');
select is((select count(*)::int from notifications where entity_id=pg_temp.c()),3,'maintenance and direct retries do not duplicate notifications');
-- Legacy GROUP failures are isolated and recover through the same existing batch.
insert into arena_daily_topics(id,title,status,opens_at,final_arguments_at,judging_at,closes_at)
 values('recovery-group-topic','Group recovery rollback fixture','closed',now()-interval '31 minutes',now()-interval '11 minutes',now()-interval '6 minutes',now()-interval '1 minute');
insert into arena_rooms(id,topic_id,capacity,opens_at,closes_at)
 values('recovery-group-room','recovery-group-topic',40,now()-interval '31 minutes',now()-interval '1 minute');
create function pg_temp.fail_group_transition() returns trigger language plpgsql as $$begin
 if new.id='recovery-group-room' then raise exception 'private group details' using errcode='P0001'; end if;
 return new;
end$$;
create trigger recovery_group_failure before update on arena_rooms for each row execute function pg_temp.fail_group_transition();
select transition_due_arena_rooms(500);
select is((select retry_status from arena_maintenance_failures where item_id='recovery-group-room'),'pending','GROUP transition failure recorded');
select is((select status::text from arena_rooms where id='recovery-group-room'),'OPEN','failed GROUP transition rolls back');
drop trigger recovery_group_failure on arena_rooms;
select transition_due_arena_rooms(500);
select is((select status::text from arena_rooms where id='recovery-group-room'),'CANCELLED','GROUP zero-vote recovery retains existing cancellation behavior');
select is((select retry_status from arena_maintenance_failures where item_id='recovery-group-room'),'resolved','successful GROUP retry resolves diagnostic');
-- A hard count cap and age retention include still-pending failures.
insert into arena_maintenance_failures(operation,item_id,sqlstate,safe_detail,last_failed_at)
 select 'clash_settlement','bounded-'||n,'P0001','Operation rejected by server rule',clock_timestamp()-interval '1 hour' from generate_series(1,1001) n;
select record_arena_maintenance_failure('clash_settlement','bounded-current','P0001');
select is((select count(*)::int from arena_maintenance_failures),1000,'failure ledger is capped at 1000 rows');
update arena_maintenance_failures set last_failed_at=clock_timestamp()-interval '8 days';
select run_maintenance(0);
select is((select count(*)::int from arena_maintenance_failures),0,'maintenance prunes diagnostics older than seven days');
select lives_ok('set constraints all immediate','recovered canonical graph satisfies terminal invariants');
select * from finish();
rollback;
