begin;
select no_plan();
insert into auth.users(id) values('00000000-0000-0000-0000-00000000a771'),('00000000-0000-0000-0000-00000000a772'),('00000000-0000-0000-0000-00000000a773');
update profiles set id='question-a',handle='question_a' where auth_user_id='00000000-0000-0000-0000-00000000a771';
update profiles set id='question-b',handle='question_b' where auth_user_id='00000000-0000-0000-0000-00000000a772';
update profiles set id='question-s',handle='question_s' where auth_user_id='00000000-0000-0000-0000-00000000a773';
select ok((select relrowsecurity from pg_class where oid='arena_question_votes'::regclass),'casual vote table has RLS');
select ok(not has_table_privilege('authenticated','arena_question_votes','select'),'voter identity table is private');
select ok(not has_table_privilege('authenticated','arena_question_votes','insert'),'direct vote insert denied');
select ok(not has_table_privilege('authenticated','arena_question_votes','update'),'direct vote total manipulation denied');
select ok(not has_column_privilege('authenticated','takes','question_origin','update'),'editorial provenance cannot be forged');
select ok(not has_function_privilege('anon','vote_arena_question(text,text,bigint,uuid)','execute'),'anonymous voting RPC denied');
set local role anon;
select throws_ok($$select vote_arena_question('known-id','A',0)$$,'42501',null,'direct anonymous known-ID vote denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a771","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select create_arena_question('techtakes','A question?','Yes',' yes ')$$,'22023',null,'case-insensitive duplicate choices refused');
select throws_ok($$select create_arena_question('techtakes','A question?',repeat('A',61),'B')$$,'22023',null,'oversize label refused');
select throws_ok($$select create_arena_question('techtakes','A question?',' ','B')$$,'22023',null,'blank choice refused');
select throws_ok($$select create_arena_question('techtakes',repeat('Q',181),'Yes','No')$$,'22023',null,'question length enforced');
select throws_ok($$select create_arena_question('techtakes','A question?','Yes','No','missing-interest')$$,'22023',null,'unknown topic refused');
create temporary table question_created as select * from create_arena_question('techtakes','Should open standards win?','Yes','No','technology');
create function pg_temp.q() returns text language sql as $$select id from question_created$$;
select is((select author_id from question_created),'question-a','server derives author');
select is((select question_origin from question_created),'human','human publisher cannot claim editorial origin');
select is((select expires_at-created_at from question_created),interval '24 hours','expiry uses existing server Take window');
select is(get_arena_question(pg_temp.q())->>'total','0','empty question has zero genuine votes');
select is(get_arena_question(pg_temp.q())->>'mySide',null,'new account has no invented vote');
select throws_ok($$select vote_arena_question(pg_temp.q(),'A',0,'00000000-0000-0000-0000-00000000a772')$$,'42501',null,'initiating account cannot differ from authenticated voting session');
select throws_ok($$select create_arena_question('techtakes','A stale account draft?','Yes','No',p_expected_auth_uid=>'00000000-0000-0000-0000-00000000a772')$$,'42501',null,'initiating account cannot differ from authenticated publishing session');
select throws_ok($$select vote_arena_question(pg_temp.q(),'DRAW',0)$$,'22023',null,'only A/B casual choices allowed');
select is(vote_arena_question(pg_temp.q(),'A',0)->>'countA','1','initial casual vote counted');
select is(vote_arena_question(pg_temp.q(),'A',0)->>'revision','1','same-side lost-response retry reuses vote');
select is(vote_arena_question(pg_temp.q(),'B',1)->>'countA','0','change removes prior side atomically');
select is(get_arena_question(pg_temp.q())->>'countB','1','changed side counted once');
select throws_ok($$select vote_arena_question(pg_temp.q(),'A',0)$$,'P0006',null,'stale revision cannot overwrite newer choice');
select throws_ok('select * from arena_question_votes','42501',null,'known voter list cannot be read through REST table');
select throws_ok($$update takes set question_origin='editorial' where id=pg_temp.q()$$,'42501',null,'direct editorial escalation denied');
reset role;
select is((select count(*)::int from rate_limit_events where actor_id='question-a' and action='arena_question_vote'),2,'only initial and actual change charge quota');
select is((select count(*)::int from arena_question_votes where take_id=pg_temp.q()),1,'one active vote per identity');
grant select on question_created to authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a772","role":"authenticated"}',true);
set local role authenticated;
select is(get_arena_question(pg_temp.q())->>'mySide',null,'another account cannot inherit first account vote');
select is(vote_arena_question(pg_temp.q(),'A',0)->>'total','2','second identity adds genuine participation');
select is(get_arena_question(pg_temp.q())->>'countA',get_arena_question(pg_temp.q())->>'countB','genuine tie retained');
select ok(not (get_arena_question(pg_temp.q()) ? 'voters'),'aggregate RPC does not expose voter list');
reset role;
select is((select count(*)::int from clashes where take_id=pg_temp.q()),0,'casual vote does not create competition');
select is((select count(*)::int from judgements j join clashes c on c.id=j.clash_id where c.take_id=pg_temp.q()),0,'casual votes are not official ballots');
select is((select count(*)::int from reputation_events where profile_id in('question-a','question-b') and clash_id is not null),0,'casual votes do not award official reputation');
update takes set status='removed' where id=pg_temp.q();
set local role authenticated;
select throws_ok($$select get_arena_question(pg_temp.q())$$,'42501',null,'removed question aggregate denied');
select throws_ok($$select vote_arena_question(pg_temp.q(),'A',1)$$,'42501',null,'same-side retry cannot bypass removal');
reset role;
update takes set status='active' where id=pg_temp.q();
insert into blocks(blocker_id,blocked_id) values('question-a','question-b');
set local role authenticated;
select throws_ok($$select vote_arena_question(pg_temp.q(),'B',1)$$,'42501',null,'blocked caller cannot change votes by known ID');
select throws_ok($$select get_arena_question(pg_temp.q())$$,'42501',null,'blocked caller cannot probe totals');
reset role;
delete from blocks where blocker_id='question-a';
insert into mutes(muter_id,muted_id) values('question-b','question-a');
set local role authenticated;
select throws_ok($$select get_arena_question(pg_temp.q())$$,'42501',null,'muted question unreadable');
reset role;
delete from mutes where muter_id='question-b';
-- Existing challenge acceptance supplies the only canonical competition graph.
set local role authenticated;
create temporary table question_offer as select create_arena_challenge(pg_temp.q(),'Open standards need a more nuanced comparison.') payload;
reset role;
grant select on question_offer to authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a771","role":"authenticated"}',true);
set local role authenticated;
create temporary table question_accepted as select resolve_arena_challenge((select (payload->>'id')::uuid from question_offer),'ACCEPT') payload;
select lives_ok($$select resolve_arena_challenge((select (payload->>'id')::uuid from question_offer),'ACCEPT')$$,'question challenge acceptance is retryable');
reset role;
select is((select count(*)::int from clashes where take_id=pg_temp.q()),1,'accepted question challenge creates one Clash');
select is((select count(*)::int from arena_rooms r join clashes c on c.id=r.clash_id where c.take_id=pg_temp.q()),1,'accepted question challenge creates one Room');
select is((select count(*)::int from judgements j join clashes c on c.id=j.clash_id where c.take_id=pg_temp.q()),0,'prior casual votes do not become judging ballots');
update takes set created_at=now()-interval '1 hour',expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.q();
set local role authenticated;
select is(get_arena_question(pg_temp.q())->>'status','closed','server expiry closes casual voting');
select throws_ok($$select vote_arena_question(pg_temp.q(),'B',1)$$,'P0003',null,'closed question refuses changes');
select throws_ok($$select vote_arena_question(pg_temp.q(),'A',0)$$,'P0003',null,'closed question refuses late first votes and retries');
select is(get_arena_question(pg_temp.q())->>'total','2','closed history retains authentic totals');
reset role;
-- Bounded precise pages, with equal timestamps, RLS and fixture exclusions.
select set_config('request.jwt.claims',null,true);
insert into takes(id,author_id,hood,text,question_a,question_b,question_origin,question_review_status,question_topic_id,created_at,expires_at)
 select 'question-page-'||lpad(n::text,3,'0'),'question-a','techtakes','Question rollback fixture '||n,'Yes','No','human','not_required','technology',date_trunc('second',now())-interval '1 second',now()+interval '23 hours' from generate_series(1,45) n;
update takes set is_runtime_fixture=true where id='question-page-001';
update takes set status='removed' where id='question-page-002';
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000a773","role":"authenticated"}',true);
set local role authenticated;
create temporary table question_page1 as select list_arena_questions('technology',null,null,20) payload;
create temporary table question_page2 as select list_arena_questions('technology',(payload#>>'{nextCursor,createdAt}')::timestamptz,payload#>>'{nextCursor,id}',20) payload from question_page1;
create temporary table question_page3 as select list_arena_questions('technology',(payload#>>'{nextCursor,createdAt}')::timestamptz,payload#>>'{nextCursor,id}',20) payload from question_page2;
select is((select jsonb_array_length(payload->'items') from question_page1),20,'first page bounded at 20');
select is((select jsonb_array_length(payload->'items') from question_page2),20,'equal-timestamp second page complete');
select is((select jsonb_array_length(payload->'items') from question_page3),3,'remaining equal-timestamp rows recovered without hidden fixtures');
select is((select count(distinct item->>'id')::int from (select payload from question_page1 union all select payload from question_page2 union all select payload from question_page3) p cross join lateral jsonb_array_elements(p.payload->'items') item),43,'pages contain no duplicates or missing visible questions');
select throws_ok($$select list_arena_questions(null,null,null,100)$$,'22023',null,'unbounded page refused');
select throws_ok($$select list_arena_questions(null,now(),null,20)$$,'22023',null,'partial cursor refused');
reset role;
insert into mutes(muter_id,muted_id) values('question-s','question-a');
set local role authenticated;
select is(jsonb_array_length(list_arena_questions('technology')->'items'),0,'discovery honors mute regardless of question popularity');
reset role;
delete from mutes where muter_id='question-s' and muted_id='question-a';
insert into rate_limit_events(actor_id,action) select 'question-s','arena_question_vote' from generate_series(1,30);
set local role authenticated;
select throws_ok($$select vote_arena_question('question-page-003','A',0)$$,'P0001',null,'server minute quota enforced');
select is(get_arena_question('question-page-003')->>'total','0','quota failure cannot partially cast vote');
reset role;
delete from rate_limit_events where actor_id='question-s';
insert into rate_limit_events(actor_id,action) select 'question-s','arena_question_vote_hour' from generate_series(1,120);
set local role authenticated;
select throws_ok($$select vote_arena_question('question-page-003','A',0)$$,'P0001',null,'server hourly quota enforced');
reset role;
select is((select count(*)::int from rate_limit_events where actor_id='question-s' and action='arena_question_vote'),0,'second quota failure rolls back first quota charge');
select lives_ok('set constraints all immediate','casual/challenge graph remains valid');
select * from finish();
rollback;
