begin;
select no_plan();
insert into auth.users(id) values('00000000-0000-0000-0000-00000000e791'),('00000000-0000-0000-0000-00000000e792'),('00000000-0000-0000-0000-00000000e793');
update profiles set id='ed-admin',role='admin' where auth_user_id='00000000-0000-0000-0000-00000000e791';
update profiles set id='ed-viewer' where auth_user_id='00000000-0000-0000-0000-00000000e792';
update profiles set id='ed-mod',role='moderator' where auth_user_id='00000000-0000-0000-0000-00000000e793';
select is((select mode from arena_editorial_config),'REVIEW_ONLY','automation defaults to review only');
select ok((select paused and publisher_id is null from arena_editorial_config),'default kill switch and missing publisher prevent publication');
select is((select count(*)::int from arena_editorial_sources),0,'no internet sources enabled by migration');
select ok((select bool_and(relrowsecurity) from pg_class where relname in('arena_editorial_config','arena_editorial_sources','arena_trend_candidates','arena_trend_observations','arena_editorial_drafts','arena_editorial_events')),'all editorial tables have RLS');
select ok(not has_table_privilege('service_role','arena_editorial_drafts','insert'),'service role has no direct editorial writes');
select ok((select bool_and(not has_sequence_privilege(r,s,'USAGE,SELECT,UPDATE')) from unnest(array['anon','authenticated','service_role']) r cross join unnest(array['public.arena_trend_observations_id_seq','public.arena_editorial_events_id_seq']) s),'private sequences cannot be read, advanced or reset by API roles');
select ok(not has_function_privilege('authenticated','arena_editorial_worker(text,uuid,jsonb)','execute'),'ordinary clients cannot invoke worker');
select ok(not has_function_privilege('anon','publish_arena_editorial(uuid,integer,boolean,uuid)','execute'),'anonymous publication denied');
set local role anon;
select throws_ok($$select arena_editorial_admin('inspect')$$,'42501',null,'anonymous inspection denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e792","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select arena_editorial_admin('inspect')$$,'42501',null,'viewer cannot inspect private drafts');
select throws_ok('select * from arena_trend_candidates','42501',null,'known direct REST table denied');
select throws_ok($$select publish_arena_editorial(gen_random_uuid(),1)$$,'42501',null,'viewer known-ID publication denied');
select throws_ok($$select publish_arena_editorial(gen_random_uuid(),1,true)$$,'42501',null,'viewer cannot impersonate automatic publisher');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e793","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select arena_editorial_admin('inspect')$$,'moderator may inspect');
select throws_ok($$select arena_editorial_admin('configure','{"mode":"LIMITED_AUTO","paused":false}')$$,'42501',null,'moderator cannot enable automation');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e791","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select arena_editorial_admin('inspect','{}','00000000-0000-0000-0000-00000000e792')$$,'42501',null,'operator account switch assertion enforced');
select lives_ok($$select arena_editorial_admin('configure','{"mode":"REVIEW_ONLY","paused":false,"publisherId":"ed-admin"}')$$,'admin explicitly configures real staff publisher');
select lives_ok($$select arena_editorial_admin('source','{"id":"ed-source-a","adapter":"rss","feedUrl":"https://first.example.org/rss","linkHost":"first.example.org","publisherGroup":"publisher-a","category":"technology","credibility":0.9,"enabled":true,"autoAllowed":true}')$$,'admin registers authorized source');
select lives_ok($$select arena_editorial_admin('source','{"id":"ed-source-b","adapter":"json","feedUrl":"https://second.example.org/feed","linkHost":"second.example.org","publisherGroup":"publisher-b","category":"technology","credibility":0.9,"enabled":true,"autoAllowed":true}')$$,'second independent source registered');
select throws_ok($$select arena_editorial_admin('source','{"id":"ed-invalid","adapter":"rss","feedUrl":"https://first.example.org/rss","linkHost":"first.example.org","publisherGroup":"publisher-a","category":"unknown","credibility":0.9}')$$,'23514',null,'unsupported category rejected');
reset role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
create temporary table ed_claim as select arena_editorial_worker('claim') payload;
select set_config('ed.run',(select payload->>'runId' from ed_claim),true);
create function pg_temp.run() returns uuid language sql as $$select current_setting('ed.run')::uuid$$;
select is(arena_editorial_worker('claim')->>'busy','true','overlapping run cannot claim active lease');
select throws_ok($$select arena_editorial_worker('work',gen_random_uuid())$$,'42501',null,'wrong worker lease rejected');
create temporary table ed_ingested as select arena_editorial_worker('ingest',pg_temp.run(),jsonb_build_object('sourceId','ed-source-a','title','Orion software release adds offline features','summary','Orion announced an offline software release.','url','https://first.example.org/orion','publishedAt',clock_timestamp()-interval '1 hour')) payload;
grant select on ed_ingested to authenticated;
create function pg_temp.cid() returns uuid language sql as $$select (payload->>'id')::uuid from ed_ingested$$;
select is(arena_editorial_worker('ingest',pg_temp.run(),jsonb_build_object('sourceId','ed-source-a','title','Orion software release adds offline features','summary','same URL replay','url','https://first.example.org/orion','publishedAt',clock_timestamp()-interval '1 hour'))->>'duplicate','true','source URL replay deduplicates');
select is(arena_editorial_worker('ingest',pg_temp.run(),jsonb_build_object('sourceId','ed-source-b','title','Offline features announced in Orion software release','summary','Orion adds offline capabilities.','url','https://second.example.org/orion','publishedAt',clock_timestamp()-interval '2 hours'))->>'id',pg_temp.cid()::text,'substantially similar headline grouped into same topic');
select is((select count(*)::int from arena_trend_candidates where id=pg_temp.cid()),1,'one canonical topic identity');
select is((select rank_details->>'independentPublishers' from arena_trend_candidates where id=pg_temp.cid()),'2','confirmation uses real independent publishers');
select throws_ok($$select arena_editorial_worker('ingest',pg_temp.run(),jsonb_build_object('sourceId','ed-source-a','title','Expired scientific report is not a current trend','summary','','url','https://first.example.org/old','publishedAt',clock_timestamp()-interval '5 days'))$$,'22023',null,'expired source refused');
select throws_ok($$select arena_editorial_worker('ingest',pg_temp.run(),jsonb_build_object('sourceId','ed-source-a','title','Wrong publisher article should fail ingestion','summary','','url','https://fiction.example.org/story','publishedAt',clock_timestamp()))$$,'22023',null,'unsupported source attribution refused');
select is(arena_editorial_worker('begin_generation',pg_temp.run(),jsonb_build_object('id',pg_temp.cid()))->>'version','1','generation reserves immutable version');
create function pg_temp.draft() returns jsonb language sql as $$select jsonb_build_object('question','For this technology release, which matters more?','sideA','More features','sideB','Better reliability','context','Orion announced an offline software release.','confidence',0.97,'needsHuman',false,'blocked',false,'kind','release_or_schedule','sourceUrls',jsonb_build_array('https://first.example.org/orion','https://second.example.org/orion'))$$;
select throws_ok($$select arena_editorial_worker('generated',pg_temp.run(),jsonb_build_object('id',pg_temp.cid(),'version',1,'draft',pg_temp.draft()||'{"sourceUrls":["https://hallucinated.example.org/story"]}','provider','mock','model','mock','promptVersion','test-1'))$$,'22023',null,'hallucinated generation source refused server-side');
select lives_ok($$select arena_editorial_worker('generated',pg_temp.run(),jsonb_build_object('id',pg_temp.cid(),'version',1,'draft',pg_temp.draft(),'provider','mock','model','mock','promptVersion','test-1'))$$,'valid grounded mock generation stored');
select is(arena_editorial_worker('generated',pg_temp.run(),jsonb_build_object('id',pg_temp.cid(),'version',1,'draft',pg_temp.draft(),'provider','mock','model','mock','promptVersion','test-1'))->>'duplicate','true','same generation retry is idempotent');
select throws_ok($$select arena_editorial_worker('generated',pg_temp.run(),jsonb_build_object('id',pg_temp.cid(),'version',1,'draft',pg_temp.draft()||'{"question":"A different question?"}','provider','mock','model','mock','promptVersion','test-1'))$$,'40001',null,'immutable generation rejects altered retry payload');
select is((select status from arena_trend_candidates where id=pg_temp.cid()),'reviewed','generation does not imply publication approval');
select throws_ok($$select publish_arena_editorial(pg_temp.cid(),1,true,pg_temp.run())$$,'42501',null,'review only blocks automatic publishing');
select is((select count(*)::int from takes where question_ai_generated),0,'review-only draft creates no Take');
-- Public staff cannot spoof worker privileges merely because they can review.
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e791","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select publish_arena_editorial(pg_temp.cid(),1)$$,'42501',null,'unapproved staff publish denied');
select lives_ok($$select arena_editorial_admin('review',jsonb_build_object('id',pg_temp.cid(),'version',1,'decision','approve'))$$,'human approval records reviewer and version');
select throws_ok($$select publish_arena_editorial(pg_temp.cid(),2)$$,'22023',null,'wrong generation version cannot publish');
create temporary table ed_published as select publish_arena_editorial(pg_temp.cid(),1) payload;
select is(publish_arena_editorial(pg_temp.cid(),1)->>'takeId',(select payload->>'takeId' from ed_published),'publication retry returns original Take');
select is(publish_arena_editorial(pg_temp.cid(),1)->>'duplicate','true','publication retry is explicitly idempotent');
reset role;
select is((select count(*)::int from takes where id=(select payload->>'takeId' from ed_published)),1,'exactly one existing Take published');
select is((select author_id from takes where id=(select payload->>'takeId' from ed_published)),'ed-admin','existing configured staff is publisher; no synthetic identity');
select is((select question_origin from takes where id=(select payload->>'takeId' from ed_published)),'editorial','editorial origin is explicit');
select ok((select question_ai_generated from takes where id=(select payload->>'takeId' from ed_published)),'AI attribution is explicit');
select is((select jsonb_array_length(question_sources) from takes where id=(select payload->>'takeId' from ed_published)),2,'publication includes actual source links');
select is((select count(*)::int from arena_question_votes where take_id=(select payload->>'takeId' from ed_published)),0,'no artificial engagement added');
select is((select count(*)::int from clashes where take_id=(select payload->>'takeId' from ed_published)),0,'automatic question is not a canonical Clash');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e792","role":"authenticated"}',true);
set local role authenticated;
select is(vote_arena_question((select payload->>'takeId' from ed_published),'A',0)->>'total','1','normal human voting works on editorial Take');
select throws_ok($$update takes set question_ai_generated=false where id=(select payload->>'takeId' from ed_published)$$,'42501',null,'client cannot remove AI attribution');
reset role;
-- Source withdrawal is trusted moderation and must not reopen on retry.
select set_config('ed.observation',(select id::text from arena_trend_observations where candidate_id=pg_temp.cid() limit 1),true);
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e791","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select arena_editorial_admin('withdraw_source',jsonb_build_object('observationId',current_setting('ed.observation')::bigint))$$,'staff withdraws identified source without direct table access');
select is(publish_arena_editorial(pg_temp.cid(),1)->>'status','removed','retry cannot reopen source-moderated publication');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e792","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select get_arena_question((select payload->>'takeId' from ed_published))$$,'42501',null,'removed editorial question is unreadable by known ID');
select throws_ok($$select vote_arena_question((select payload->>'takeId' from ed_published),'A',1)$$,'42501',null,'same-side retry cannot bypass source moderation');
reset role;
-- Root-owned deterministic fixtures exercise publication gates without provider calls.
create function pg_temp.fixture(p_category text,p_title text,p_question text,p_human boolean default false,p_blocked boolean default false) returns uuid language plpgsql as $$
declare cid uuid:=gen_random_uuid(); context text:='Neutral release context '||cid::text; a text; b text;
begin
 a:='More features'; b:='Better reliability';
 insert into arena_trend_candidates(id,topic_key,tokens,title,summary,category,status,generation_version,attempts) values(cid,cid::text,arena_editorial_tokens(p_title),p_title,context,p_category,'reviewed',1,1);
 insert into arena_trend_observations(candidate_id,source_id,url,title,summary,published_at,language) values
 (cid,'ed-source-a','https://first.example.org/'||cid,p_title,context,clock_timestamp()-interval '1 hour','en'),
 (cid,'ed-source-b','https://second.example.org/'||cid,p_title,context,clock_timestamp()-interval '1 hour','en');
 insert into arena_editorial_drafts(candidate_id,version,question,side_a,side_b,context,confidence,needs_human,blocked,kind,source_urls,provider,model,prompt_version)
 values(cid,1,p_question,a,b,context,0.98,p_human,p_blocked,'release_or_schedule',array['https://first.example.org/'||cid,'https://second.example.org/'||cid],'mock','mock','test-1'); return cid;
end $$;
select set_config('ed.next',pg_temp.fixture('technology','Vega software release launches portable tools','For this technology release, which matters more?')::text,true);
update arena_editorial_config set mode='LIMITED_AUTO',paused=false,daily_cap=1,category_cap=1;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'P0001',null,'global daily cap includes removed publications');
update arena_editorial_config set daily_cap=6;
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'P0001',null,'category daily cap enforced');
update arena_editorial_config set category_cap=5,paused=true;
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'42501',null,'kill switch blocks eligible auto candidate');
update arena_editorial_config set paused=false,mode='OFF';
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'42501',null,'OFF blocks all fresh publication');
update arena_editorial_config set mode='LIMITED_AUTO';
update arena_editorial_sources set auto_allowed=false where id='ed-source-b';
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'42501',null,'unapproved auto source requires human review');
update arena_editorial_sources set auto_allowed=true,publisher_group='publisher-a' where id='ed-source-b';
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'42501',null,'syndicated publisher cannot fake independent confirmation');
update arena_editorial_sources set publisher_group='publisher-b' where id='ed-source-b';
update arena_trend_observations set published_at=clock_timestamp()-interval '4 days' where candidate_id=current_setting('ed.next')::uuid;
select throws_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'42501',null,'freshness rechecked at publication');
update arena_trend_observations set published_at=clock_timestamp()-interval '1 hour' where candidate_id=current_setting('ed.next')::uuid;
select lives_ok($$select publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())$$,'restricted grounded low-risk candidate may auto publish');
select is(publish_arena_editorial(current_setting('ed.next')::uuid,1,true,pg_temp.run())->>'duplicate','true','automatic retry is idempotent');
select set_config('ed.risk',pg_temp.fixture('current_affairs','Orion release brings new current affairs discussion','For this technology release, which matters more?')::text,true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.risk')::uuid,1,true,pg_temp.run())$$,'42501',null,'current affairs cannot auto publish even if model says low risk');
select set_config('ed.risk',pg_temp.fixture('technology','Minister accused after software release announcement','For this technology release, which matters more?')::text,true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.risk')::uuid,1,true,pg_temp.run())$$,'42501',null,'potentially harmful allegations require human review despite model flags');
select set_config('ed.risk',pg_temp.fixture('technology','Orion release introduces a new computer interface','Is every critic stupid?')::text,true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.risk')::uuid,1,true,pg_temp.run())$$,'42501',null,'arbitrary loaded model wording cannot enter auto mode');
select set_config('ed.risk',pg_temp.fixture('technology','Orion release introduces another computer interface','For this technology release, which matters more?',false,true)::text,true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.risk')::uuid,1,true,pg_temp.run())$$,'22023',null,'blocked output cannot publish');
update arena_editorial_config set publisher_id='ed-viewer';
select set_config('ed.risk',pg_temp.fixture('technology','Polaris software release announces astronomy tools','For this technology release, which matters more?')::text,true);
select throws_ok($$select publish_arena_editorial(current_setting('ed.risk')::uuid,1,true,pg_temp.run())$$,'42501',null,'ordinary user cannot be silently used as system publisher');
update arena_editorial_config set publisher_id='ed-admin';
select ok(jsonb_array_length(arena_editorial_worker('work',pg_temp.run())->'items')<=12,'actual worker query returns bounded candidate context');
select lives_ok($$select arena_editorial_worker('fail',pg_temp.run(),jsonb_build_object('id',current_setting('ed.risk'),'reason','provider_unavailable'))$$,'provider failure records retryable state');
select is((select status from arena_trend_candidates where id=current_setting('ed.risk')::uuid),'failed','failed job does not claim success');
select ok((select retry_at>clock_timestamp() from arena_trend_candidates where id=current_setting('ed.risk')::uuid),'exponential retry backoff uses server clock');
select throws_ok($$select arena_editorial_worker('begin_generation',pg_temp.run(),jsonb_build_object('id',current_setting('ed.risk')))$$,'22023',null,'backoff prevents immediate repeated paid requests');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000e791","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select arena_editorial_admin('retry',jsonb_build_object('id',current_setting('ed.risk')))$$,'authorized operator can request safe retry');
reset role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is(arena_editorial_worker('begin_generation',pg_temp.run(),jsonb_build_object('id',current_setting('ed.risk')))->>'version','2','retry reserves new generation version without overwriting history');
select is((select count(*)::int from arena_editorial_drafts where candidate_id=current_setting('ed.risk')::uuid),1,'prior generation retained for audit');
select lives_ok($$select arena_editorial_worker('source_failure',pg_temp.run(),'{"sourceId":"ed-source-a"}')$$,'safe source failure can be diagnosed');
select ok((select count(*)>0 from arena_editorial_events where reason='source_unavailable:ed-source-a'),'source diagnostics identify configured source without upstream response text');
select is(arena_editorial_worker('release',pg_temp.run()),'{}'::jsonb,'worker lease released');
select throws_ok($$select arena_editorial_worker('work',pg_temp.run())$$,'42501',null,'released lease cannot mutate or inspect worker context');
select ok((select count(*)>0 from arena_editorial_events where operation='approved' and reason='human_decision'),'audit retains human decisions');
select ok((select count(*)>0 from arena_editorial_events where operation='approved' and reason='restricted_auto_policy'),'audit distinguishes automatic policy decisions');
select lives_ok('set constraints all immediate','editorial Take graph respects existing constraints');
select * from finish();
rollback;
